### ISSUE TITLE
Crash on Android 12 emulator (API32, x86_64) created by Android studio

### ISSUE THREAD

**Issue by klauslaiRC** [msintuneappsdk/ms-intune-app-sdk-android#113] opened 2022-05-10 08:32 UTC
**Describe the bug:**

**To Reproduce**
1. Company portal app is installed
2. launch app build with Intune SDK
3. app crash immediately

**Expected behavior:**
App launched, and navigate to MS account login page

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler: java.lang.RuntimeException: Unable to instantiate application com.glip.foundation.app.DebugGlipApplication package com.ringcentral.intune: com.microsoft.intune.mam.libs.MAMLibraryException: After attempting to re-unpack MAM libs, there were still issues loading them.`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1364)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6695)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.app.ActivityThread.access$1500(ActivityThread.java:256)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.os.Handler.dispatchMessage(Handler.java:106)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.os.Looper.loopOnce(Looper.java:201)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.os.Looper.loop(Looper.java:288)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at android.app.ActivityThread.main(ActivityThread.java:7842)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at java.lang.reflect.Method.invoke(Native Method)`
`05-10 17:43:07.283  9724  9724 E ncaughtExceptionHandler:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)]`
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: **Android 12 emulator from Android studio**
 - OS: **API: 32, CPU/ABI: x86_64**

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 
-  **8.6 version**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
-  **kotlin/java/android**
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated? 
- Who is the customer?
-   **It's in test**
- Do you see a trend with it only being reproduced on a specific device?
-  **just in android 12 emulator**

**Additional context:**

**Comment by bannus** [comment] 2022-05-12 17:42
Hi @klauslaiRC, we have not observed this on Android 12 emulators. Could you reproduce the problem, then follow the directions at https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android to upload logs? Please relay the incident ID here and we can take a look.

**Comment by klauslaiRC** [comment] 2022-05-13 01:12
I have reproduce the bug through below steps:
Scenario 1:
1. install company portal
2. install app build with intune SDK
3. launch app 2 times
4. app crashed

Scenario 2:
1. continue Scenario 1
2. login my account in company portal & setup device
3. launch app 7 times
4. app crashed all the time

Incident ID: XW3NGRPB

**Comment by codylund** [comment] 2022-05-17 20:48
The root of the crash appears to be an `UnsatisfiedLinkError`, which results from attempting to load an x86_64 shared library on an arm64 emulator.

```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.ringcentral.intune/mam_libs/x86_64/libwolfssl.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
	at java.lang.Runtime.load0(Runtime.java:929)
	at java.lang.System.load(System.java:1620)
	at com.microsoft.intune.mam.libs.NativeLibLoaderBase.libLoad(NativeLibLoaderBase.java:331)
	at com.microsoft.intune.mam.libs.-$$Lambda$-PdndStpcj7jOCuMEsqcl1fD8lE.load(Unknown Source:2)
	at com.microsoft.intune.mam.libs.NativeLibLoaderBase.tryLoadNativeLib(NativeLibLoaderBase.java:338)
	... 28 more
```

Based on code inspection, it appears that the emulator may be incorrectly reporting its ABI via build properties. I am unable to reproduce this issue with `system-images;android-32;google_apis;x86_64`, rev 3 as acquired via SDK Manager in Android Studio. 

@klauslaiRC, can you confirm your emulator is truly running an x86_64 image? As a workaround, can you try using the above emulator image instead?

**Comment by joakley-msft** [comment] 2022-05-24 14:40
@klauslaiRC a few more questions here
1. Are you seeing this error with multiple/all apps, or specifically with your app? If you're seeing with other apps, could you list the ones you've tried? For example, does it also reproduce with our sample app at https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App? If specifically with your app, could you share a sample project with reproduces the problem?
2. What host OS are you running on? It theoretically *shouldn't* matter to the emulator but would be good to rule out if we can given the differing behaviors you're seeing vs what our team is seeing on the same emulator image.

**Comment by klauslaiRC** [comment] 2022-06-02 00:50
oh @meghandaly  I'm very sorry, I've been busy with the verification of the intune app recently, i'm running on macOS, version 11.6.6

**Comment by klauslaiRC** [comment] 2022-07-21 07:07
hi @bannus  could you please provider an app file? I didn't find an installable program to use in the git repo

**Comment by joakley-msft** [comment] 2022-08-30 21:24
@klauslaiRC are you still experiencing this problem? Since it sounds as though the issue reproduces only with your app, we would need that app or a minimal sample to investigate further.

**Comment by joakley-msft** [comment] 2022-11-17 13:38
Closing due to lack of sufficient info to investigate. If you are still facing this issue and are able to provide more information in the future, please feel free to open a new issue.

**Closed by joakley-msft** 2022-11-17 13:38 UTC
Labels: Need More Information
