### ISSUE TITLE
Coroutine 1.6.0 doesn’t seem to be supported by MAM Intune SDK 8.3.0

### ISSUE THREAD

**Issue by MathieuCalba** [msintuneappsdk/ms-intune-app-sdk-android#97] opened 2022-02-03 22:28 UTC
**Describe the bug:**
When building our app that has Coroutines 1.6.0 dependency (https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.6.0), we have the following error:
````
[00:19:05]: ▸ Execution failed for task ':app:transformClassesWithMamifyTransformForCiFullRelease'.
[00:19:05]: ▸ > Cannot inherit from final class
````

If we choose the 1.5.2 version of Coroutines (https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.5.2), we don’t have the error.

In the generated report or when running the command using `--stacktrace` and `--debug` I don’t see more information about which class is concerned. The report doesn't give any more information either.

**To Reproduce**
1. Add Coroutines 1.6.0 dependency
2. Build
3. See error

The Taskr sample doesn’t compile so couldn’t try on it easily.

**Expected behavior:**
Mamification should work.

**Screenshots and logs:**
There is nothing mentioned in the logs even with the --debug option. And the report doesn’t mention any issue.

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 8.3.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Kotlin & Java
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? -
- Who is the customer? LumApps
- Do you see a trend with it only being reproduced on a specific device? -

**Comment by bannus** [comment] 2022-02-28 21:29
Thanks for the report, we are investigating.

(internal tracking: #13307832)

**Comment by MathieuCalba** [comment] 2022-04-29 21:59
Hello, any updates on this?

**Comment by bannus** [comment] 2022-05-12 17:55
Sorry, still no timeline to share currently.

**Comment by MathieuCalba** [comment] 2022-07-05 08:22
Hello @joakley-msft, with the latest version, we no longer have the issue. We can close this issue.

**Comment by joakley-msft** [comment] 2022-07-05 11:38
Thanks Matthieu. Since we can't reproduce and you no longer have this issue, I'm closing it out.

**Closed by joakley-msft** 2022-07-05 11:38 UTC
Labels: Closed - Closed by User
