### ISSUE TITLE
App crash with error "androidx.fragment.app.FragmentActivity.onStart+40" on Android 14 devices if Company portal app is installed on the device

### ISSUE THREAD

**Issue by decisionslab2** [msintuneappsdk/ms-intune-app-sdk-android#198] opened 2023-11-17 05:28 UTC
## Questions to Ask Before Submission

1. Does your app compile and launch successfully without the Intune App SDK? - yes
2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues? - yes
3. Are you using the latest version of the [SDK and Plugin]? - yes

## Summary

Please briefly describe the issue you are experiencing.
- After upgrading the InTune SDK to the latest version, 10.0.0, the app seems to crash on launch when attempting to reopen it after closing. We attempted to resolve the issue by uninstalling the Company Portal App, and it worked fine. However, after reinstalling the Company Portal app and trying to launch the app again, it crashed.

We have integrated the InTune SDK into a Flutter project, and everything works fine on Android 13. However, on Android 14, we encounter crash issues on the app's second launch.

From the logs, we believe that the issue could be related to "androidx.fragment." We have seen similar issues related to androidx.fragment:fragment and reported for the previous version of the InTune SDK.

Link: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/130

## Details

- **Intune Android App SDK Version:** 10.0.0
- **Gradle Version:**  gradle-7.3.1
- **AGP Version:**
- **Operating System (Mac, Linux, Windows) and Version:** Latest
- **Android Studio Version:** Android Studio Giraffe | 2022.3.1 Patch 1

## Logs
 ```---------------------------- PROCESS STARTED (23837) for package com.meetingdecisions.androidApp ----------------------------
2023-11-16 15:20:44.931 23837-23884 nativeloader            com.meetingdecisions.androidApp      D  Configuring clns-9 for other apk . target_sdk_version=33, uses_libraries=ALL, library_path=/data/app/~~A4GVvdNuE3VUk6XXNPV_GQ==/com.microsoft.windowsintune.companyportal-NCim0Afl--aU41wEgm1-rw==/lib/x86_64:/data/app/~~A4GVvdNuE3VUk6XXNPV_GQ==/com.microsoft.windowsintune.companyportal-NCim0Afl--aU41wEgm1-rw==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand
2023-11-16 15:20:45.299 23837-23837 ziparchive              com.meetingdecisions.androidApp      W  Unable to open '/data/app/~~RqHbw8Mk6i8jcoIcVJERww==/com.google.android.trichromelibrary_604506638-RJESDDASSEXNz_3sipGDig==/base.dm': No such file or directory
2023-11-16 15:20:45.299 23837-23837 ziparchive              com.meetingdecisions.androidApp      W  Unable to open '/data/app/~~RqHbw8Mk6i8jcoIcVJERww==/com.google.android.trichromelibrary_604506638-RJESDDASSEXNz_3sipGDig==/base.dm': No such file or directory
2023-11-16 15:20:45.299 23837-23837 ions.androidApp         com.meetingdecisions.androidApp      W  Entry not found
2023-11-16 15:20:45.299 23837-23837 nativeloader            com.meetingdecisions.androidApp      D  Configuring clns-10 for other apk /data/app/~~RqHbw8Mk6i8jcoIcVJERww==/com.google.android.trichromelibrary_604506638-RJESDDASSEXNz_3sipGDig==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~ZEE5WoSkSQCN4yNvh_lFlQ==/com.google.android.webview-H7mnM1OVAWdAPTGenGeOTg==/lib/x86_64:/data/app/~~ZEE5WoSkSQCN4yNvh_lFlQ==/com.google.android.webview-H7mnM1OVAWdAPTGenGeOTg==/base.apk!/lib/x86_64:/data/app/~~RqHbw8Mk6i8jcoIcVJERww==/com.google.android.trichromelibrary_604506638-RJESDDASSEXNz_3sipGDig==/base.apk!/lib/x86_64, permitted_path=/data:/mnt/expand
2023-11-16 15:20:45.304 23837-23837 libc                    com.meetingdecisions.androidApp      A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc in tid 23837 (ions.androidApp), pid 23837 (ions.androidApp)
---------------------------- PROCESS STARTED (23939) for package com.meetingdecisions.androidApp ----------------------------
2023-11-16 15:20:45.483 23937-23937 DEBUG                   pid-23937                            A  Cmdline: com.meetingdecisions.androidApp
2023-11-16 15:20:45.483 23937-23937 DEBUG                   pid-23937                            A  pid: 23837, tid: 23837, name: ions.androidApp  >>> com.meetingdecisions.androidApp <<<
2023-11-16 15:20:45.487 23937-23937 DEBUG                   pid-23937                            A        #28 pc 0000000000b9e1b6  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (com.pichillilorenzo.flutter_inappwebview.MyCookieManager.getCookieManager+10)
2023-11-16 15:20:45.487 23937-23937 DEBUG                   pid-23937                            A        #30 pc 0000000000b9e392  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (com.pichillilorenzo.flutter_inappwebview.MyCookieManager.<init>+38)
2023-11-16 15:20:45.487 23937-23937 DEBUG                   pid-23937                            A        #32 pc 0000000000b9b692  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine+114)
2023-11-16 15:20:45.487 23937-23937 DEBUG                   pid-23937                            A        #34 pc 0000000000b9b72c  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (com.pichillilorenzo.flutter_inappwebview.InAppWebViewFlutterPlugin.onAttachedToEngine+44)
2023-11-16 15:20:45.487 23937-23937 DEBUG                   pid-23937                            A        #36 pc 0000000000c2bbd4  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add+220)
2023-11-16 15:20:45.488 23937-23937 DEBUG                   pid-23937                            A        #38 pc 0000000000c44626  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.plugins.GeneratedPluginRegistrant.registerWith+146)
2023-11-16 15:20:45.488 23937-23937 DEBUG                   pid-23937                            A        #49 pc 0000000000c33114  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins+0)
2023-11-16 15:20:45.489 23937-23937 DEBUG                   pid-23937                            A        #54 pc 0000000000c2156e  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.embedding.android.FlutterFragmentActivity.configureFlutterEngine+22)
2023-11-16 15:20:45.489 23937-23937 DEBUG                   pid-23937                            A        #56 pc 00000000003bbb62  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (com.example.decisions_mobile.MainActivity.configureFlutterEngine+54)
2023-11-16 15:20:45.489 23937-23937 DEBUG                   pid-23937                            A        #58 pc 0000000000c21e78  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.embedding.android.FlutterFragment.configureFlutterEngine+20)
2023-11-16 15:20:45.489 23937-23937 DEBUG                   pid-23937                            A        #60 pc 0000000000c1f008  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach+116)
2023-11-16 15:20:45.490 23937-23937 DEBUG                   pid-23937                            A        #62 pc 0000000000c21f4a  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (io.flutter.embedding.android.FlutterFragment.onAttach+22)
2023-11-16 15:20:45.490 23937-23937 DEBUG                   pid-23937                            A        #64 pc 0000000000300a8e  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.Fragment.performAttach+98)
2023-11-16 15:20:45.490 23937-23937 DEBUG                   pid-23937                            A        #66 pc 00000000002f922e  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentStateManager.attach+422)
2023-11-16 15:20:45.490 23937-23937 DEBUG                   pid-23937                            A        #68 pc 00000000002f9c4e  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentStateManager.moveToExpectedState+286)
2023-11-16 15:20:45.490 23937-23937 DEBUG                   pid-23937                            A        #70 pc 00000000002f6b3e  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentManager.executeOpsTogether+554)
2023-11-16 15:20:45.491 23937-23937 DEBUG                   pid-23937                            A        #72 pc 00000000002f7b70  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute+168)
2023-11-16 15:20:45.491 23937-23937 DEBUG                   pid-23937                            A        #74 pc 00000000002f4c4a  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentManager.execPendingActions+42)
2023-11-16 15:20:45.491 23937-23937 DEBUG                   pid-23937                            A        #76 pc 00000000002f6288  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentManager.dispatchStateChange+84)
2023-11-16 15:20:45.491 23937-23937 DEBUG                   pid-23937                            A        #78 pc 00000000002f5e92  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentManager.dispatchActivityCreated+22)
2023-11-16 15:20:45.491 23937-23937 DEBUG                   pid-23937                            A        #80 pc 00000000002f16c0  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentController.dispatchActivityCreated+8)
2023-11-16 15:20:45.492 23937-23937 DEBUG                   pid-23937                            A        #82 pc 00000000002f05f8  /data/app/~~gq-MGNj_fg9mEF1U0l-EbQ==/com.meetingdecisions.androidApp-XKaKZL1WH5PBesTWWKsmtg==/oat/x86_64/base.vdex (androidx.fragment.app.FragmentActivity.onStart+40)
---------------------------- PROCESS ENDED (23837) for package com.meetingdecisions.androidApp ----------------------------
---------------------------- PROCESS ENDED (23939) for package com.meetingdecisions.androidApp ----------------------------```

**Comment by nabiarshad** [comment] 2023-11-22 11:32
Recently, a new security patch was released, and it has successfully resolved the issue. I am unable to reproduce it, and everything is working as expected on the devices where the issues were identified, namely the Google Pixel Pro and Samsung devices. We can go ahead and close this issue

**Closed** 2023-11-22 13:58 UTC
Labels: External
