### ISSUE TITLE
javassist.CannotCompileExceptio compile error

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#90] opened 2022-01-05 08:50 UTC
Mamification failed: onMAMCreate (Landroid/os/Bundle;)V in com.medallia.digital.mobilesdk.c0: conflict: int and androidx.appcompat.app.AppCompatActivity
javassist.CannotCompileException: onMAMCreate (Landroid/os/Bundle;)V in com.medallia.digital.mobilesdk.c0: conflict: int and androidx.appcompat.app.AppCompatActivity
	at javassist.expr.ExprEditor.doit(ExprEditor.java:122)
	at javassist.CtClassType.instrument(CtClassType.java:1554)
	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClass(BuildTimeMamifier.java:454)
	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClass(BuildTimeMamifier.java:391)
	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClasses(BuildTimeMamifier.java:195)
	at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:107)
	at com.microsoft.intune.mam.MamifyTransformBase.transform(MamifyTransformBase.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
	at com.android.build.gradle.internal.profile.NoOpAnalyticsService.recordBlock(NoOpAnalyticsService.kt:72)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:506)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:491)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:474)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:106)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:271)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:249)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:83)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:37)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:47)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:37)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:50)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:54)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:35)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:174)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeAndStoreInCache(BuildCacheStep.java:150)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$2(BuildCacheStep.java:124)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$executeWithCache$3(BuildCacheStep.java:124)
	at org.gradle.internal.Try$Success.map(Try.java:162)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithCache(BuildCacheStep.java:83)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:45)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:29)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:99)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:92)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:85)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:42)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:91)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:106)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:51)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:72)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:46)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:86)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:32)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:43)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:31)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$2.withWorkspace(ExecuteActionsTaskExecuter.java:284)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:174)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by boyzhang-msft** [comment] 2022-01-06 17:44
Hi @Nash123-start , thank you for reporting the issue. I just have a few clarification/follow up questions before further investigation:
- Does your app build successfully without integrating MAM SDK?
- Could you post the MAM relevant sections in your build.gradle?
- Could you post the generated build plugin HTML report? You can generate the report with `--report` option when running the MAM gradle build plugin.
- It looks like the exception happened when trying to rewrite the onCreate method in com.medallia.digital.mobilesdk.c0 class, is it possible to provide a minimum app that repros this error? Or copy and paste the method body of onCreate of that class?

**Comment by Nash123-start** [comment] 2022-01-07 06:15
1.Yes I can build the app successfully without integrating MAM SDK?
2.In my build.gradle I add the dependence :Implementation "com.medallia.digital.mobilesdk:android-sdk:${rootProject.ext.medalliaVersion}"   medalliaVersion = "3.9.1"
 maven {
            allowInsecureProtocol = true
            url 'http://nexus.lab.rcch.ringcentral.com:8888/nexus/content/repositories/glip-mobile-snapshots'
        }

  classpath "org.javassist:javassist:3.22.0-GA"
        classpath files("MAMSDK/com.microsoft.intune.mam.build.jar")

apply plugin: 'com.microsoft.intune.mam'

 // Include the MAM SDK
    implementation files('../MAMSDK/Microsoft.Intune.MAM.SDK.aar')

    // Include MSAL
    implementation 'com.microsoft.identity.client:msal:2.0.8'

3.com.medallia.digital.mobilesdk.c0 class this  class is in the mobilesdk aar file and  is obfuscated

package com.medallia.digital.mobilesdk;

import android.content.Intent;
import android.content.MutableContextWrapper;
import android.os.Bundle;
import android.os.Handler;
import android.view.View;
import android.view.ViewGroup;
import android.widget.RelativeLayout;
import android.widget.RelativeLayout.LayoutParams;
import androidx.appcompat.app.AppCompatActivity;
import com.medallia.digital.mobilesdk.FormCommunicator.g;
import com.medallia.digital.mobilesdk.MedalliaWebView.d;
import com.medallia.digital.mobilesdk.MedalliaWebView.e;
import com.medallia.digital.mobilesdk.R.id;
import com.medallia.digital.mobilesdk.j0.d.a;

abstract class c0 extends AppCompatActivity implements g, d {
    protected j2 a;
    private boolean b = true;
    private boolean c = false;
    private long d;
    private MedalliaWebView e;
    private long f;
    private Handler g;
    private d4 h;

    c0() {
        Handler var1;
        var1 = new Handler.<init>();
        this.g = var1;
        d4 var2;
        var2 = new d4() {
            {
                this.a = var1;
            }

            public void a() {
                if (!c0.a(this.a).isRenderFinished() && !this.a.isFinishing()) {
                    if (!s0.a) {
                        AnalyticsBridge var10000 = AnalyticsBridge.getInstance();
                        String var10001 = this.a.a.getFormId();
                        Long var1 = c0.b(this.a);
                        FormViewType var2 = this.a.a.getFormViewType();
                        FormTriggerType var3 = this.a.a.getFormType();
                        var10000.reportFormLoadSpinnerEvent(var10001, var1, var2, var3);
                    }

                    c0.a(this.a, true);
                }

            }
        }.<init>();
        this.h = var2;
    }

    private void d() {
        if (this.a != null) {
            r3.e("FormId: " + this.a.getFormId() + " close was called");
            if (this.e != null) {
                ((RelativeLayout)this.findViewById(id.medallia_form_webview_layout)).removeView(this.e);
                if (this.e.getParent() != null) {
                    ((ViewGroup)this.e.getParent()).removeView(this.e);
                }

                if (s0.a) {
                    this.e.clearAndDestroy();
                } else {
                    a7.b().a(this.e);
                }
            }

            if (!s0.a) {
                a var10000;
                String var10001;
                FormTriggerType var1;
                FormViewType var2;
                String var3;
                String var4;
                if (!this.c) {
                    var10000 = com.medallia.digital.mobilesdk.j0.d.a.d;
                    var10001 = this.a.getFormId();
                    var1 = this.a.getFormType();
                    var2 = this.a.getFormViewType();
                    var3 = o3.c().a();
                    var4 = this.a.getFormLanguage();
                    com.medallia.digital.mobilesdk.j0.d.a(var10000, var10001, var1, var2, -1L, var3, var4);
                }

                if (this.b) {
                    var10000 = com.medallia.digital.mobilesdk.j0.d.a.b;
                    var10001 = this.a.getFormId();
                    var1 = this.a.getFormType();
                    var2 = this.a.getFormViewType();
                    var3 = o3.c().a();
                    var4 = this.a.getFormLanguage();
                    com.medallia.digital.mobilesdk.j0.d.a(var10000, var10001, var1, var2, 0L, var3, var4);
                }

                if (!this.a.f().p()) {
                    var10000 = com.medallia.digital.mobilesdk.j0.d.a.c;
                    var10001 = this.a.getFormId();
                    c0 var10002 = this;
                    c0 var10003 = this;
                    FormTriggerType var5 = this.a.getFormType();
                    FormViewType var6 = var10003.a.getFormViewType();
                    String var7 = o3.c().a();
                    var3 = var10002.a.getFormLanguage();
                    com.medallia.digital.mobilesdk.j0.d.a(var10000, var10001, var5, var6, -1L, var7, var3);
                }
            }
        }

    }

    private void c() {
        d4 var1;
        var1 = new d4() {
            {
                this.a = var2;
            }

            public void a() {
                c0.this.e.setFormCommunicatorListener(this.a);
                c0.this.e.setLoadingListener(this.a);
                if (c0.this.e.isRenderFinished()) {
                    c0.this.a(false);
                }

                c0.this.e.setLayoutParams(new LayoutParams(-1, -1));
                if (c0.this.e.getParent() != null) {
                    ((ViewGroup)c0.this.e.getParent()).removeView(c0.this.e);
                }

                ((RelativeLayout)c0.this.findViewById(id.medallia_form_webview_layout)).addView(c0.this.e);
                if (c0.this.e.isRenderFinished()) {
                    c0.this.c = true;
                    if (!s0.a) {
                        a var10000 = com.medallia.digital.mobilesdk.j0.d.a.d;
                        String var10001 = c0.this.a.getFormId();
                        <undefinedtype> var10002 = this;
                        <undefinedtype> var10003 = this;
                        FormTriggerType var4 = c0.this.a.getFormType();
                        FormViewType var1 = c0.this.a.getFormViewType();
                        String var2 = o3.c().a();
                        String var3 = c0.this.a.getFormLanguage();
                        com.medallia.digital.mobilesdk.j0.d.a(var10000, var10001, var4, var1, 0L, var2, var3);
                    }
                }

            }
        }.<init>(this);
        this.runOnUiThread(var1);
    }

    private void a(boolean var1) {
        View var2 = this.findViewById(id.medallia_progress_bar);
        byte var3;
        if (var1) {
            var3 = 0;
        } else {
            var3 = 8;
        }

        var2.setVisibility(var3);
    }

    private e a(j2 var1, boolean var2) {
        e var3;
        if (var2) {
            var3 = com.medallia.digital.mobilesdk.MedalliaWebView.e.a;
        } else {
            var3 = com.medallia.digital.mobilesdk.MedalliaWebView.e.b;
        }

        if (var1.h()) {
            var3 = com.medallia.digital.mobilesdk.MedalliaWebView.e.c;
        }

        return var3;
    }

    protected abstract void f();

    protected void onCreate(Bundle var1) {
        Intent var2;
        if ((var2 = this.getIntent()) != null && var2.hasExtra("com.medallia.digital.mobilesdk.form_data")) {
            this.f = System.currentTimeMillis();
            this.a = (j2)var2.getSerializableExtra("com.medallia.digital.mobilesdk.form_data");
            boolean var3 = var2.getBooleanExtra("com.medallia.digital.mobilesdk.is_show_form", false);
            if (s0.a) {
                MutableContextWrapper var4 = y3.c().d();
                e var5 = com.medallia.digital.mobilesdk.MedalliaWebView.e.a;
                j2 var6 = this.a;
                (this.e = new MedalliaWebView(var4, var5, var6, 0L)).loadUrl("about:blank");
                this.e.setConfiguration(a7.b().a());
                this.e.load((d)null);
            } else {
                this.e = a7.b().c(this.a(this.a, var3));
            }

            boolean var10000 = var3;
            var3 = var2.getBooleanExtra("com.medallia.digital.mobilesdk.vuln_enabled", true);
            long var8 = f5.d;
            this.d = var8 = var2.getLongExtra("com.medallia.digital.mobilesdk.spinner_delay", var8);
            if (var10000) {
                this.g.postDelayed(this.h, var8);
            }

            if (var2.getBooleanExtra("com.medallia.digital.mobilesdk.inherit_orientation", false)) {
                this.setRequestedOrientation(3);
            } else {
                this.setRequestedOrientation(10);
            }

            if (!s0.a && var3 && this.getWindow() != null) {
                this.getWindow().addFlags(8192);
            }

            c0 var9 = this;
            c0 var10001 = this;
            c0 var10002 = this;
            c0 var10004 = this;
            p2 var10005 = k6.a(this.a.g());
            int var7 = var10005.a();
            var10004.overridePendingTransition(var7, var10005.b());
            var10002.onCreate(var1);
            var10001.f();
            var9.c();
        } else {
            this.e();
        }
    }

    protected void onPause() {
        super.onPause();
        MedalliaWebView var1;
        if ((var1 = this.e) != null) {
            var1.setFormCommunicatorListener((g)null);
            this.e.setLoadingListener((d)null);
        }

    }

    protected void onResume() {
        super.onResume();
        MedalliaWebView var1;
        if ((var1 = this.e) != null) {
            var1.setFormCommunicatorListener(this);
            this.e.setLoadingListener(this);
        }

    }

    public void onDestroy() {
        super.onDestroy();
        if (this.isFinishing()) {
            this.d();
            MedalliaWebView var1;
            if ((var1 = this.e) != null && var1.isPreload()) {
                this.e.reloadWebView();
            }
        }

    }

    public void onBackPressed() {
        super.onBackPressed();
        this.e();
    }

    public void finish() {
        c0 var10000 = this;
        super.finish();
        p2 var10001 = k6.b(this.a.g());
        int var1 = var10001.a();
        var10000.overridePendingTransition(var1, var10001.b());
    }

    public void onClose() {
        d4 var1;
        var1 = new d4() {
            public void a() {
                c0.this.b = false;
                c0.this.e();
            }
        }.<init>();
        this.runOnUiThread(var1);
    }

    public void onReady() {
    }

    public void a() {
        d4 var1;
        var1 = new d4() {
            public void a() {
                c0.this.a(false);
            }
        }.<init>();
        this.runOnUiThread(var1);
    }

    public void b() {
        if (!this.c) {
            this.c = true;
            if (!s0.a) {
                a var10000 = com.medallia.digital.mobilesdk.j0.d.a.d;
                String var10001 = this.a.getFormId();
                c0 var10002 = this;
                FormTriggerType var1 = this.a.getFormType();
                FormViewType var2 = this.a.getFormViewType();
                long var3 = System.currentTimeMillis() - this.f;
                String var6 = o3.c().a();
                String var5 = var10002.a.getFormLanguage();
                com.medallia.digital.mobilesdk.j0.d.a(var10000, var10001, var1, var2, var3, var6, var5);
            }

        }
    }

    protected void e() {
        Handler var1;
        d4 var2;
        if ((var1 = this.g) != null && (var2 = this.h) != null) {
            var1.removeCallbacks(var2);
            this.g.removeCallbacksAndMessages((Object)null);
            this.g = null;
            this.h = null;
        }

        this.finish();
    }
}

This is the class in the sdk aar file

4.Could you post the generated build plugin HTML report? You can generate the report with --report option when running the MAM gradle build plugin.
As for this question, the build run failed and I can't find the report in the output. Could you please tell me how to run this plugin

**Comment by boyzhang-msft** [comment] 2022-01-10 14:30
Thanks for the detailed information. Could you post your complete `build.gradle` file? The snippet doesn't seem to include all MAM related parts. I was looking for something similar to the samples provided here: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#gradle-build-plugin

For 4, to generate the report, you can add 
```
intunemam {
    report = true
}
```
as mentioned here: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#reporting

**Comment by Nash123-start** [comment] 2022-01-12 05:23
Hi, I had put the demo to the github, there is the link:
https://github.com/Nash123-start/ApplicationTestForIntunes
You can download the demo code here

**Comment by Nash123-start** [comment] 2022-01-12 05:40
I have pushed the demo to the GitHub, there is the link:https://github.com/Nash123-start/ApplicationTest

**Comment by Nash123-start** [comment] 2022-01-18 00:48
Is there anything updated?

**Comment by joakley-msft** [comment] 2022-01-28 21:36
Thank you for the project. We can reproduce using your demo, and this does appear to be an Intune bug. This will be fixed in a forthcoming SDK release.

**Comment by joakley-msft** [comment] 2022-04-21 12:25
This is fixed in SDK 8.6.1

**Closed by joakley-msft** 2022-04-21 12:25 UTC
Labels: Pending Future Release
