### ISSUE TITLE
Crash Due to AgentIpcException

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#112] opened 2022-05-05 08:21 UTC
Caused by com.microsoft.intune.mam.client.ipc.exceptions.AgentIpcException
Android threw IllegalArgumentException. Agent flags: 0doze: false; app inactive: false; agent inactive: false; device interactive: true; power save: false; agent disabled: false; provider disabled: false. Method invoked: methodName: mustCheckPolicies; returnType: int
com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.doAgentIpc (Unknown Source:184)
com.microsoft.intune.mam.client.ipc.ContentProviderEndpointProxy$EndpointProxyInvocationHandler.lambda$invoke$0$ContentProviderEndpointProxy$EndpointProxyInvocationHandler (Unknown Source:107)
com.microsoft.intune.mam.client.ipc.-$$Lambda$ContentProviderEndpointProxy$EndpointProxyInvocationHandler$cVECf9axIoLRDqJ_Y6oDZqcwBXs.call (Unknown Source:10)
com.microsoft.intune.mam.client.identity.IdentityCallable.call (Unknown Source:38)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

**Comment by bannus** [comment] 2022-05-11 22:50
Duplicate of #105

**Closed by bannus** 2022-05-11 22:50 UTC
