### ISSUE TITLE
java.lang.AssertionError: Attempt to access uninitialized OfflineComponents

### ISSUE THREAD

**Issue by cabanasn** [msintuneappsdk/ms-intune-app-sdk-android#50] opened 2020-09-09 18:45 UTC
I'm trying to migrate my Kotlin app to Android X and the app is crashing at startup because it is unable to initialize OfflineComponents.

App crashes in the following line:
`val mgr = MAMComponents.get(MAMEnrollmentManager::class.java)`

**Screenshots and logs:**
![Screen Shot 2020-09-09 at 15 43 56](https://user-images.githubusercontent.com/7597858/92640169-46da4980-f2b3-11ea-91bd-f5addf4bc24b.png)

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 7.0.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Kotlin
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? CipherHealth
- Do you see a trend with it only being reproduced on a specific device? No

**Comment by MathieuCalba** [comment] 2021-06-17 08:10
Hello, I had the same issue with the same crash report, it disappeared later, and now it happens again.
Is there any information about what is happening here?

**Intune App SDK for Android (please complete the following information):**

- What version of the Intune SDK are you using? Are you using the latest version? 7.2.2
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Kotlin
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? LumApps
- Do you see a trend with it only being reproduced on a specific device? No

**Comment by sameepsharma** [comment] 2021-06-17 10:12
Hello did you guys figure out the problem?

**Comment by MathieuCalba** [comment] 2021-06-24 08:38
@sameepsharma nope, it seems to be depending on how I build me app, if it is from the CLI, I have the error, while from Android Studio it works, which is bananas…

**Comment by joakley-msft** [comment] 2021-09-07 15:19
This is definitely unexpected, and counter to the experience of most apps. If anyone is still experiencing this issue, are you able to provide a minimal sample project which reproduces the problem?

**Comment by ukjbrown** [comment] 2021-09-22 15:08
Did anyone make any progress with the above error? I have an application with multiple productFlavors. One of those flavors works without any issue, the other throws the `java.lang.AssertionError: Attempt to access uninitialized OfflineComponents` exception when calling `MAMEnrollmentManager mgr = MAMComponents.get(MAMEnrollmentManager.class);`

**Comment by meghandaly** [comment] 2021-11-04 13:43
@cabanasn or @MathieuCalba are either of you still experiencing this issue? If so, can you provide a minimal sample so that we may help address it? Also of interest might be @bannus ' suggestion above.

**Comment by bannus** [comment] 2021-12-09 22:39
Closing -- please re-open if this still occurs after making the configuration change I suggested:

> @ukjbrown This may be a configuration issue with the SDK's Gradle Build Plugin ([docs here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#gradle-build-plugin)). The stack from the root post suggests that `OrchidApp.onCreate` was not rewritten. Your build might not be applying the plugin to all flavors. Please check your configuration and if the issue still reproduces, build logs and/or a sample project will help us investigate further.

**Closed by bannus** 2021-12-09 22:39 UTC
Labels: Need More Information
