### ISSUE TITLE
Android Service with android:isolatedProcess="true" not working with intune SDK.

### ISSUE THREAD

**Issue by pradiptilala** [msintuneappsdk/ms-intune-app-sdk-android#76] opened 2021-09-21 12:34 UTC
**Describe the bug:**
I have an app which uses intune sdk for android. We want to integrate a service with with android:isolatedProcess="true" for root detection related functionality on our App. 
But, android Service with **android:isolatedProcess="true"** not able to work with our App with already integrated Intune SDK.

**We have also tried to create an separate sample App with intune and with a service having set android:isolatedProcess in Manifest. But this service is not working.**

**To Reproduce**
1. Create a sample app with service having set android:isolatedProcess in Manifest. Decleration in manifest is as below:
```
        <service
            android:name=".RemoteService"
            android:useAppZygote="true"
            android:isolatedProcess="true" />
```
2. We are using bindService method to bind to the service. As shown below:
```
        Intent intent = new Intent(this,IsolatedService.class);
        /*Binding to an isolated service */
        getApplicationContext().bindService(intent, mIsolatedServiceConnection, BIND_AUTO_CREATE);
```

3. When running this sample, it is able to connect to isolated process and onServiceConnected() method of ServiceConnection is called.
4. Then we have integrated the intune library with this App.
5. When running sample app after integrating intune SDK, it is not able to run the service having set android:isolatedProcess.
You can integrate Intune sdk and can check with these existing app which have isolated process to check this scenario: [MagiskDetector](https://github.com/vvb2060/MagiskDetector)
OR
[DetectMagiskHide](https://github.com/darvincisec/DetectMagiskHide)

**Expected behavior:**
It's expected that service with android:isolatedProcess flag set work normally with App which have already Intune SDK integrated. Isolated process do work with intune SDK for Android App.

**logs:**
- If your app is not experiencing an issue during build: **There is no logs at build time.**
- If your app is experiencing an issue post build? : **App is not crashing so, Android studio not shows any logs.**

**Smartphone (please complete the following information):**
 - **It's an issue on all devices.** I have checked it on Redmi note 3 (Android M) and POCO f1 (Android 10 Q)

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? : We are using latest version : **Version 7.6.0**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? :  **App is based in Java.**
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device? : **No there is no trend. It's not working on any device.**

**Questions**
- **Can we run isolated process with Intune SDK on Android App?**
- **Is there any workaround/solution to use isolated process with Intune SDK?**

**Comment by rygo-msft** [comment] 2021-09-22 21:21
Hi @pradiptilala,

Can you provide more information about your issue?

What exactly is failing for your app? Is the service not starting at all, or does it start but not in an isolated process?

Can you share logs from the Company Portal after reproducing the issue?
https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android

**Comment by pradiptilala** [comment] 2021-09-23 11:25
@rygo-msft 
Uploaded Log with Incident ID: **FXCH3MDG**

Service is starting when we have AndroidManifest.xml declaration as below: (Service is starting)
```
<service
            android:name="com.darvin.security.IsolatedService"
            android:enabled="true" />
```


But once I add flag android:isolatedProcess="true" to service's AndroidManifest.xml declaration as Shown below,  service not starting at all. (Isolated process not starting at all)

```
 <service
            android:name="com.darvin.security.IsolatedService"
            android:enabled="true"
            **android:isolatedProcess="true"** />
```

Isolated process is not starting when App has Intune SDK integrated and It does not matter whether company portal is installed or not on device.

**Comment by pradiptilala** [comment] 2021-09-27 06:21
@rygo-msft  **Could you please guide us with this as we are at a critical phase for our release.**

**Comment by rygo-msft** [comment] 2021-09-27 15:41
Unfortunately, we don't have a general solution right now for isolated processes because of the requirement to communicate with the Company Portal. We are discussing potential options for you.

@pradiptilala, can you share more information about what your isolated service will be doing? Is magisk / root detection an accurate representation of your use case, or does your service do something else? Do you access any files written by other app processes? Does your isolated service communicate with any other apps or system services?

**Comment by pradiptilala** [comment] 2021-10-01 11:53
@rygo-msft

Please find more information about questions:

- Is Magisk / root detection an accurate representation of your use case, or does your service do something else? Do you access any files written by other app processes?
**- Answer:** Accurate representation of your use case is to detect Magisk presence on device. Our App is not writing any files from other app process.

- Does your isolated service communicate with any other apps or system services?
**- Answer:** No, Our isolated service does not communicate with other app or system service.

**You can find reference to logic implemented in these libraries for isolated processes:**
**DetectMagiskHide:**
Isolated process will try to find the black listed mount paths and su paths in "/proc/<pid>/mounts" file. 
Isolated process implementation : https://github.com/darvincisec/DetectMagiskHide/blob/master/app/src/main/java/com/darvin/security/IsolatedService.java
Native functions for the same:
https://github.com/darvincisec/DetectMagiskHide/blob/master/app/src/main/c/native-lib.c

**Similary in MagiskDetector :**
Isolated process in MagiskDetector check for su path presence and check mount information.
Native code Reference link : https://github.com/vvb2060/MagiskDetector/blob/master/app/src/main/jni/vvb2060.c

**Comment by meghandaly** [comment] 2021-11-03 19:55
We have made a fix for this that will be available in a future release. There is no known workaround in the meantime.

**Comment by meghandaly** [comment] 2021-12-27 15:20
Thank you for your patience! 

Please see the latest release, [Release Version 8.3.0 ](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/8.3.0), for guidance on how to address this issue with the latest MAM SDK.

**Closed by meghandaly** 2021-12-27 15:20 UTC
Labels: Pending Future Release
