### ISSUE TITLE
MAM Gradle plugin incompatible with AGP 7.2.0/7.2.1

### ISSUE THREAD

**Issue by Shashank-IET** [msintuneappsdk/ms-intune-app-sdk-android#119] opened 2022-07-21 18:08 UTC
## **Describe the bug:**
The app is crashing as soon as launched. The crash originates in the Application's `attachBaseContext(..)` method.
Been using the version 8.3.0 and it was working just fine. I have recently upgraded the project's Gradle version & AGP version to 7.4.2 & 7.2.1 respectively & the app started crashing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the app icon
2. Splash screen appears and the app crashes.

**Expected behaviour:**
A routined app launch was expected

**Screenshots and logs:**
```
  E AndroidRuntime: Process: com.adobe.reader, PID: 776
  E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.adobe.reader.MyApplication: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.microsoft.intune.mam.client.ComponentsContainer.get(java.lang.Class)' on a null object reference
  E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
  E AndroidRuntime: at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152)
  E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
  E AndroidRuntime: at android.app.ActivityThread.access$1500(ActivityThread.java:274)
  E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
  E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:107)
  E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
  E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8167)
  E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
  E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
  E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
  E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.microsoft.intune.mam.client.ComponentsContainer.get(java.lang.Class)' on a null object reference
  E AndroidRuntime: at com.microsoft.intune.mam.client.InterfaceComponentsAccess.get(InterfaceComponentsAccess.java:30)
  E AndroidRuntime: at com.microsoft.intune.mam.client.CachedBehaviorProvider.getComponent(CachedBehaviorProvider.java:42)
  E AndroidRuntime: at com.microsoft.intune.mam.client.CachedBehaviorProvider.get(CachedBehaviorProvider.java:33)
  E AndroidRuntime: at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getBehavior(MAMPackageManagement.java:409)
  E AndroidRuntime: at com.microsoft.intune.mam.client.content.pm.MAMPackageManagement.getPackageInfo(MAMPackageManagement.java:228)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.zze.<init>(com.google.android.play:core@@1.10.2:1)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.SplitCompat.<init>(com.google.android.play:core@@1.10.2:2)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.SplitCompat.zzi(com.google.android.play:core@@1.10.2:1)
  E AndroidRuntime: at com.google.android.play.core.splitcompat.SplitCompat.install(com.google.android.play:core@@1.10.2:1)
  E AndroidRuntime: at com.adobe.reader.MyApplication.attachBaseContext(ARApp.java:290)
  E AndroidRuntime: at android.app.Application.attach(Application.java:370)
  E AndroidRuntime: at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
  E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
  E AndroidRuntime: ... 10 more
```

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52s, Oneplus 5 , & verified on multiple emulator instances.
 - OS: Android 10, Android 12, Android 11

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- - using 8.3.0. Verified with 8.6.1 also, still crashing
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- - Native Android Application using Java & Kotlin
- ~For errors during build, does the app build without Intune SDK integration?~
- - Not applicable
- For errors post build, does the app launch without being Intune SDK integrated?
- - YES
- Who is the customer?
- - End User
- Do you see a trend with it only being reproduced on a specific device?
- - Nothing device specific.

## **Additional context:**
Below are some unique findings I have about this crash. Hope it helps
Everything was working fine when I was using
| module                          | version | 
| ---------------------- | ------- |
| Gradle                            | 6.8      |
| Android Gradle Plugin  | 4.2      |
| Intune SDK version       | 8.3.0   |
- Things start to break as soon as I upgrade gradle & AGP to 7.4.2 & 7.2.1. Tried updating the intune SDK also, but didn't work out.
- I tried with a downgraded the AGP version & observed that upto version 4.2.2 things tend to work fine. ie. Gradle (v7.4.2) | Intune (v8.3.0) | AGP (v4.2.2) work fine

### Additionally
- The failure only happening when running with progaurd rules in debug build. Progaurd for debug & release variants are same.
- - Release variant works perfectly fine (Progaurd enabled)
- - Debug variant without the progaurd ie. `minifyEnabled false` , also works perfectly fine.
- I tried commenting out the `SplitCompat.install(...)` part but it didn't work. Instead gave below error
```
com.adobe.reader I/MAMInfo: MAMInfo initialized. Debug=false, Agent=PRODUCTION, ManagedDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=true, FullBackupContent=true, DataExtractionRules=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=true, IsolatedProcessesAllowed=false
com.adobe.reader I/MAMComponents: Not initializing MAM classes because the MDM package is not installed.
com.adobe.reader I/MAMComponents: Not initializing MAM classes because the MDM package is not installed.
com.adobe.reader I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
com.adobe.reader I/FirebaseCrashlytics: Initializing Firebase Crashlytics 18.2.6 for com.adobe.reader
com.adobe.reader I/DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:14 and remote module com.google.android.gms.measurement.dynamite:0
com.adobe.reader I/DynamiteModule: Selected local version of com.google.android.gms.measurement.dynamite
com.adobe.reader I/FirebaseInitProvider: FirebaseApp initialization successful
com.adobe.reader D/AndroidRuntime: Shutting down VM
com.adobe.reader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adobe.reader, PID: 12547
    java.lang.LinkageError: Method android.database.Cursor com.adobe.reader.MyFileProvider.query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String) overrides final method in class Lcom/microsoft/intune/mam/client/content/MAMContentProvider; (declaration of 'com.adobe.reader.misc.MyFileProvider' appears in /data/app/com.adobe.reader-Y5AlV0eFreYdEddeijnH-w==/base.apk!classes2.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6972)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
- The same error also prompted up when I manually declared `MyApplication.java` class to inherit `MAMApplication` overriding the `onMAMCreate` method.

**Comment by bannus** [comment] 2022-07-21 19:28
Hi @Shashank-IET. We are aware of an issue that causes the MAM Gradle plugin to be broken on projects using Android Gradle Plugin version 7.2.0 or 7.2.1 due to an AGP bug: https://issuetracker.google.com/issues/232438924. MAM SDK rewrites will not be applied to app project sources, which will typically cause the app to crash on launch.

The fix for the AGP bug will be released in AGP 7.40-alpha03 (released), 7.3.0-beta02 (released) and 7.2.2 (unreleased). Until 7.2.2 is released, please remain on 7.1.3 or below. We have confirmed that the issue is resolved using 7.3.0-beta03, so we'd recommend using that version for development work.

**Comment by Shashank-IET** [comment] 2022-07-27 09:29
Thanks. this helped.

**Comment by meghandaly** [comment] 2022-08-17 18:47
AGP 7.2.2 released on August 3rd and included the required fix. 

From the [AGP Release](https://developer.android.com/studio/releases/gradle-plugin#7-2-0) site:

> 7.2.2 (August 2022)
> This minor update corresponds to the release of Android Studio Chipmunk Patch 2 and includes the following bug fixes:

> [Issue #232438924](https://issuetracker.google.com/issues/232438924): AndroidGradlePlugin version 7.2 breaks transform API when used along with ASM API
> [Issue #231037948](https://issuetracker.google.com/issues/231037948): AGP 7.2.0-rc01 :buildSrc:generatePrecompiledScriptPluginAccessors - shadow/bundletool/com/android/prefs/AndroidLocation$AndroidLocationException

A future version of the SDK will include a specific check to ensure neither 7.2.0 or 7.2.1 are being used for integrated MAM app development.

**Closed by meghandaly** 2022-08-17 18:47 UTC
Labels: Bug, Pending Future Release
