### ISSUE TITLE
MAM Intune SDK don’t work when KSP is enabled

### ISSUE THREAD

**Issue by MathieuCalba** [msintuneappsdk/ms-intune-app-sdk-android#96] opened 2022-02-03 22:11 UTC
**Describe the bug:**
When building our app with KSP enabled for Moshi, there is an error at compile time:
````
> Task :app:transformClassesWithMamifyTransformForCiFullRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMamifyTransformForCiFullRelease'.
> com.android.build.api.transform.TransformException: com.microsoft.intune.mam.rewrite.RewriteException: java.nio.file.NoSuchFileException: /Users/mcalba/Git/android/app/build/generated/ksp/ciFullRelease/classes
````

There is indeed no `classes` file or directory in this folder when building with KSP. They are classes in a `kotlin` folder instead.

Using Moshi with KAPT works and using Moshi with KSP without MAM Intune works also.

**To Reproduce**
1. Add Moshi using KSP (see https://github.com/square/moshi/blob/master/CHANGELOG.md#version-1130)
2. Build
3. See error

The Taskr sample doesn’t compile so couldn’t try on it easily.

**Expected behavior:**
MAM Intune SDK should work with KSP

**Screenshots and logs:**
There is nothing mentioned in the logs even with the `--debug` option. And the report doesn’t mention any issue.

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 8.3.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Java & Kotlin
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? -
- Who is the customer? LumApps
- Do you see a trend with it only being reproduced on a specific device? -

**Comment by bannus** [comment] 2022-02-28 21:30
Thanks for the report, we are investigating.

(internal tracking #13307832)

**Comment by MathieuCalba** [comment] 2022-04-29 21:59
Hello, any updates on this?

**Comment by bannus** [comment] 2022-05-12 17:54
Sorry, no timeline to share currently.

**Comment by joakley-msft** [comment] 2022-05-24 20:23
Hi @MathieuCalba, my apologies for the delay on this on our side. I attempted to investigate, but am not able to reproduce. When I added Moshi to one of our test apps, including adding codegen through KSP for an adapter the build succeeded without issue. Could you provide a sample app which reproduces this problem?

**Comment by bannus** [comment] 2022-07-12 18:46
Closing as we were unable to reproduce. If a sample can be provided that reproduces the issue, please re-open.

**Closed** 2022-07-12 18:46 UTC
Labels: Bug, Need More Information
