### ISSUE TITLE
Help to update intune-app-wrapping-tool-android support Android 12+

### ISSUE THREAD

**Issue by xzetic05** [msintuneappsdk/ms-intune-app-sdk-android#140] opened 2022-11-14 07:39 UTC
**Describe the bug:**
The ms-intune-app-sdk-android supported the latest SDK but we are still using the [intune-app-wrapping-tool-android](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android) for our Company Portal application. This wrapping tool don't have any update anymore to support SDK 32 of Android 12.

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 12

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Ionic Capacitor
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by bannus** [comment] 2022-11-14 21:15
Duplicate of https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/issues/64

**Closed by bannus** 2022-11-14 21:15 UTC
