### ISSUE TITLE
Copy/paste from unmanaged apps wasn't blocked

### ISSUE THREAD

**Issue by Chenxi1123Tan** [msintuneappsdk/ms-intune-app-sdk-android#210] opened 2024-02-02 10:40 UTC
# Intune Android App SDK Policy Enforcement Issue
 
## Questions to Ask Before Submission
 
1. Have you completed the exit criteria for each phase in the [Intune App SDK for Android Integration Guide]?
**- yes**
2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues?
**- yes**
3. Are you using the latest version of the [SDK]?
**- yes**
 
## Repro Steps
 
Please provide concrete steps to reproduce the issue you are encountering.
 
1. Set 'Policy managed apps' as the copy/paste restriction in console.
2. Copy content from an unmanaged app.
3. Paste the copied content in the Copilot app which is a managed app.
 
**Expectation:**
Block copy/paste from unmanaged apps to Copilot app.
 
**Observation:**
Can paste the content from unmanaged apps to Copilot app.
 
## Details
 
- **Intune Android App SDK Version:** 10.0 
- **Android Device Make and Model:**  Oneplus 9R 
- **Android Device OS Version:** Android 13
- **Android Studio Version:**
 
### Company Portal Logs
 
**Incident ID:**
 
For guidance, see [Report a problem in Company Portal or Intune app for Android].
 
### Screenshots and Recordings
[recordings ](https://microsoftapc-my.sharepoint.com/:v:/g/personal/chenxitan_microsoft_com/ETSSJpeRBn5Ft8ouatZm2WMBDIg8pzWe8UONHtxLj47oXg?e=IgiZh0&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
 
## AndroidX Dependencies
 
If your app includes any AndroidX libraries, please list them here, along with the version info:

 
- NA
 
## Third-Party Library Dependencies
 
If your app includes any third-party libraries, please list them here, along with the version info:
 
- NA
 

[Intune App SDK for Android Integration Guide]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase1
[Report a problem in Company Portal or Intune app for Android]: https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by Chenxi1123Tan** [comment] 2024-02-02 10:42
[log.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/14138864/log.txt)

https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/158297350/7f531fa3-acf0-4e8d-86b1-d1f631cc2f6a

**Comment by bannus** [comment] 2024-02-14 17:38
Hi @Chenxi1123Tan, I cannot reproduce this issue. If you are still seeing this, can you upload Company Portal Logs and share the incident ID as requested in the issue template above?

**Comment by mukeshk-ms** [comment] 2024-04-16 15:40
closing since there is not enough information

**Closed by mukeshk-ms** 2024-04-16 15:40 UTC
Labels: Closed - Not Enough Info
